### ISSUE TITLE
Violating basic principles in the "One-App-Eight-Architectures" code

### ISSUE THREAD

**Issue by tomassliz** [objcio/app-architecture#1]
In "One-App-Eight-Architectures" project you have created a [model directly in a view controller](https://github.com/objcio/app-architecture/blob/ee561c7b804b0a91f2411123f7cd5c4190a1221d/One-App-Eight-Architectures/MultiPattern/ViewController.swift#L5). I understand that for simplification you have chosen this path. But for example in MVVM the view should not know about model. I think that this can be confusing for some people. I know - it's simple example app. But from the whole point of view - this is a book about app architectures so why to violate their basic principles and dependencies and bend them over when you try to teach them?

**Comment by chriseidhof** [comment]
Thanks for reporting this. There are many things that could be different in that very app (IOU's, type-safety, etc.). The focus is not at all on how the model is created, but how it is used. We decided to take that shortcut for the sake of simplicity!
