### ISSUE TITLE
One-App-Eight-Architectures mvc extension question

### ISSUE THREAD

**Issue by BMinas** [objcio/app-architecture#10]
I'm trying to understand why `MultiViewController` was extended for the MVC version.  The function `mvcDidLoad()` and the action `mvcButtonPressed()` are typically just included in the ViewController class.  I looked through the accompanying book and some of the videos and didn't see any mention of extending the ViewController under the MVC pattern.  I also didn't see that with the Recordings application.  Is there some benefit, structural or clarity to this?

**Comment by dimagimburg** [comment]
@BMinas I think that it is just for convenience and visual separation of code.

**Comment by BMinas** [comment]
Thank you @dimagimburg.  Obviously I over analyze things...
