### ISSUE TITLE
Could you pls upload the starter project?

### ISSUE THREAD

**Issue by zhengyaoyuan** [objcio/app-architecture#4]
So that I can complete it by myself. Thx

**Comment by floriankugler** [comment]
@zhengyaoyuan What do you mean by starter project?

**Comment by zhengyaoyuan** [comment]
@floriankugler I mean the project with basic setup. So that I can complete the code following the video.

**Comment by floriankugler** [comment]
@zhengyaoyuan Do you mean the project we use in the "eight architectures" video? If so, that's already in the repository. Just delete the contents of `viewDidLoad` and everything after that :-)

**Comment by zhengyaoyuan** [comment]
Thx
